// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: grpc/proto.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ITUDatabase_TestConnection_FullMethodName = "/ITUDatabase/TestConnection"
	ITUDatabase_PlaceBid_FullMethodName       = "/ITUDatabase/PlaceBid"
	ITUDatabase_PrintStatus_FullMethodName    = "/ITUDatabase/PrintStatus"
	ITUDatabase_AddBidder_FullMethodName      = "/ITUDatabase/AddBidder"
)

// ITUDatabaseClient is the client API for ITUDatabase service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ITUDatabaseClient interface {
	TestConnection(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	PlaceBid(ctx context.Context, in *Bid, opts ...grpc.CallOption) (*Ack, error)
	PrintStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error)
	AddBidder(ctx context.Context, in *Bidder, opts ...grpc.CallOption) (*Empty, error)
}

type iTUDatabaseClient struct {
	cc grpc.ClientConnInterface
}

func NewITUDatabaseClient(cc grpc.ClientConnInterface) ITUDatabaseClient {
	return &iTUDatabaseClient{cc}
}

func (c *iTUDatabaseClient) TestConnection(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ITUDatabase_TestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTUDatabaseClient) PlaceBid(ctx context.Context, in *Bid, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ITUDatabase_PlaceBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTUDatabaseClient) PrintStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, ITUDatabase_PrintStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTUDatabaseClient) AddBidder(ctx context.Context, in *Bidder, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ITUDatabase_AddBidder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ITUDatabaseServer is the server API for ITUDatabase service.
// All implementations must embed UnimplementedITUDatabaseServer
// for forward compatibility.
type ITUDatabaseServer interface {
	TestConnection(context.Context, *Empty) (*Empty, error)
	PlaceBid(context.Context, *Bid) (*Ack, error)
	PrintStatus(context.Context, *Empty) (*Result, error)
	AddBidder(context.Context, *Bidder) (*Empty, error)
	mustEmbedUnimplementedITUDatabaseServer()
}

// UnimplementedITUDatabaseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedITUDatabaseServer struct{}

func (UnimplementedITUDatabaseServer) TestConnection(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestConnection not implemented")
}
func (UnimplementedITUDatabaseServer) PlaceBid(context.Context, *Bid) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceBid not implemented")
}
func (UnimplementedITUDatabaseServer) PrintStatus(context.Context, *Empty) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintStatus not implemented")
}
func (UnimplementedITUDatabaseServer) AddBidder(context.Context, *Bidder) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBidder not implemented")
}
func (UnimplementedITUDatabaseServer) mustEmbedUnimplementedITUDatabaseServer() {}
func (UnimplementedITUDatabaseServer) testEmbeddedByValue()                     {}

// UnsafeITUDatabaseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ITUDatabaseServer will
// result in compilation errors.
type UnsafeITUDatabaseServer interface {
	mustEmbedUnimplementedITUDatabaseServer()
}

func RegisterITUDatabaseServer(s grpc.ServiceRegistrar, srv ITUDatabaseServer) {
	// If the following call pancis, it indicates UnimplementedITUDatabaseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ITUDatabase_ServiceDesc, srv)
}

func _ITUDatabase_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITUDatabaseServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITUDatabase_TestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITUDatabaseServer).TestConnection(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITUDatabase_PlaceBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITUDatabaseServer).PlaceBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITUDatabase_PlaceBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITUDatabaseServer).PlaceBid(ctx, req.(*Bid))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITUDatabase_PrintStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITUDatabaseServer).PrintStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITUDatabase_PrintStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITUDatabaseServer).PrintStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITUDatabase_AddBidder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bidder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITUDatabaseServer).AddBidder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITUDatabase_AddBidder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITUDatabaseServer).AddBidder(ctx, req.(*Bidder))
	}
	return interceptor(ctx, in, info, handler)
}

// ITUDatabase_ServiceDesc is the grpc.ServiceDesc for ITUDatabase service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ITUDatabase_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ITUDatabase",
	HandlerType: (*ITUDatabaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestConnection",
			Handler:    _ITUDatabase_TestConnection_Handler,
		},
		{
			MethodName: "PlaceBid",
			Handler:    _ITUDatabase_PlaceBid_Handler,
		},
		{
			MethodName: "PrintStatus",
			Handler:    _ITUDatabase_PrintStatus_Handler,
		},
		{
			MethodName: "AddBidder",
			Handler:    _ITUDatabase_AddBidder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto.proto",
}
